/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.4.3. DO NOT MODIFY.
*/
`timescale 100fs/100fs
module topEntity
    ( // Inputs
      input  CLK // clock
    , input [7:0] SWITCHES

      // Outputs
    , output wire [3:0] SS_AN
    , output wire [6:0] SS_SEG
    , output wire  SS_DP
    );
  wire [6:0] c$app_arg;
  wire [6:0] c$app_arg_0;
  wire [6:0] c$vec;
  wire [3:0] SS__dc_arg_res;
  wire [3:0] c$vec_0;
  wire [11:0] SS;

  // map begin
  genvar i;
  generate
  for (i=0; i < 7; i = i + 1) begin : map
    wire  map_in;
    assign map_in = c$app_arg_0[i*1+:1];
    wire  map_out;
    wire [0:0] c$app_arg_1;
    wire  result;
    assign map_out = result;

    assign c$app_arg_1 = map_in ? 1'b1 : 1'b0;

    assign result = ~ (c$app_arg_1);


    assign c$app_arg[i*1+:1] = map_out;
  end
  endgenerate
  // map end

  assign c$vec = (SWITCHES[7-1 : 0]);

  // map begin
  genvar i_0;
  generate
  for (i_0=0; i_0 < 7; i_0 = i_0 + 1) begin : map_0
    wire  map_in_0;
    assign map_in_0 = c$vec[i_0*1+:1];
    wire  map_out_0;
    assign map_out_0 = (map_in_0) == 1'b1;


    assign c$app_arg_0[i_0*1+:1] = map_out_0;
  end
  endgenerate
  // map end

  assign c$vec_0 = {1'b0,   1'b0,   1'b0,   1'b1};

  // map begin
  genvar i_1;
  generate
  for (i_1=0; i_1 < 4; i_1 = i_1 + 1) begin : map_1
    wire  map_in_1;
    assign map_in_1 = c$vec_0[i_1*1+:1];
    wire  map_out_1;
    wire [0:0] c$app_arg_2;
    wire  result_0;
    assign map_out_1 = result_0;

    assign c$app_arg_2 = map_in_1 ? 1'b1 : 1'b0;

    assign result_0 = ~ (c$app_arg_2);


    assign SS__dc_arg_res[i_1*1+:1] = map_out_1;
  end
  endgenerate
  // map end

  assign SS = {SS__dc_arg_res,   c$app_arg,
               1'b1};

  assign SS_AN = SS[11:8];

  assign SS_SEG = SS[7:1];

  assign SS_DP = SS[0:0];


endmodule

